name: Github Pages deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'github-pages'

    steps:
    - name: Set env variables
      env:
        NEXT_PUBLIC_GITHUB_GRAPHQL_BEARER_TOKEN: ${{ env.NEXT_PUBLIC_GITHUB_GRAPHQL_BEARER_TOKEN }}
        NEXT_PUBLIC_STRAPI_GRAPHQL_BEARER_TOKEN: ${{ env.NEXT_PUBLIC_STRAPI_GRAPHQL_BEARER_TOKEN }}
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
        
    - name: Installing my packages üì¶
      run: npm ci

    - name: Build my App üî®
      run: npm run build && npm run export && touch ./out/.nojekyll

    - name: Deploy üöÄ
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: out